id: A519A1868
title: 'The Concentration of Blessings: Red Tārā Lineage Prayer'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:04:37.441563
  last_modified_at: 2022-02-28 23:04:37.441571
